name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command run
      description: The exact command you ran.
      render: shell
      placeholder: chainsaw trace src/index.ts --chain lodash

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS:
        - chainsaw version (`chainsaw --version`):
        - Language of target codebase (TypeScript/Python):
      render: text
